// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

import (
	"github.com/timenglesf/personal-site/internal/shared"
	"github.com/timenglesf/personal-site/ui/template/components"
)

func DisplayFlashAlert(flashMsg shared.FlashMessage) templ.Component {
	switch flashMsg.Type {
	case "success":
		return components.SuccessAlert(flashMsg.Message, "success_alert", "mb-6")
	case "warning":
		return components.WarningAlert(flashMsg.Message, "warning_alert", "mb-6")
	case "error":
		return components.ErrorAlert(flashMsg.Message, "error_alert", "mb-6")
	}
	return nil
}
